//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2.ServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tentakiller.org/show", ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Parameter 'getStudentsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tentakiller.org/show/getStudents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApplication2.ServiceReference.getStudentsResponse getStudents(ConsoleApplication2.ServiceReference.getStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tentakiller.org/show/getStudents", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication2.ServiceReference.getStudentsResponse> getStudentsAsync(ConsoleApplication2.ServiceReference.getStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tentakiller.org/show/getExams", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getExams();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tentakiller.org/show/getExams", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getExamsAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStudents", WrapperNamespace="http://tentakiller.org/show", IsWrapped=true)]
    public partial class getStudentsRequest {
        
        public getStudentsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStudentsResponse", WrapperNamespace="http://tentakiller.org/show", IsWrapped=true)]
    public partial class getStudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tentakiller.org/show", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] getStudentsResult;
        
        public getStudentsResponse() {
        }
        
        public getStudentsResponse(string[][] getStudentsResult) {
            this.getStudentsResult = getStudentsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : ConsoleApplication2.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ConsoleApplication2.ServiceReference.WebServiceSoap>, ConsoleApplication2.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication2.ServiceReference.getStudentsResponse ConsoleApplication2.ServiceReference.WebServiceSoap.getStudents(ConsoleApplication2.ServiceReference.getStudentsRequest request) {
            return base.Channel.getStudents(request);
        }
        
        public string[][] getStudents() {
            ConsoleApplication2.ServiceReference.getStudentsRequest inValue = new ConsoleApplication2.ServiceReference.getStudentsRequest();
            ConsoleApplication2.ServiceReference.getStudentsResponse retVal = ((ConsoleApplication2.ServiceReference.WebServiceSoap)(this)).getStudents(inValue);
            return retVal.getStudentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication2.ServiceReference.getStudentsResponse> ConsoleApplication2.ServiceReference.WebServiceSoap.getStudentsAsync(ConsoleApplication2.ServiceReference.getStudentsRequest request) {
            return base.Channel.getStudentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication2.ServiceReference.getStudentsResponse> getStudentsAsync() {
            ConsoleApplication2.ServiceReference.getStudentsRequest inValue = new ConsoleApplication2.ServiceReference.getStudentsRequest();
            return ((ConsoleApplication2.ServiceReference.WebServiceSoap)(this)).getStudentsAsync(inValue);
        }
        
        public System.Data.DataSet getExams() {
            return base.Channel.getExams();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getExamsAsync() {
            return base.Channel.getExamsAsync();
        }
    }
}
